(cl:defpackage fremenserver-msg
  (:use )
  (:export
   "<FREMENACTION>"
   "FREMENACTION"
   "<FREMENACTIONFEEDBACK>"
   "FREMENACTIONFEEDBACK"
   "<FREMENACTIONGOAL>"
   "FREMENACTIONGOAL"
   "<FREMENACTIONRESULT>"
   "FREMENACTIONRESULT"
   "<FREMENFEEDBACK>"
   "FREMENFEEDBACK"
   "<FREMENGOAL>"
   "FREMENGOAL"
   "<FREMENRESULT>"
   "FREMENRESULT"
  ))

