// Generated by gencpp from file fremenserver/FremenActionGoal.msg
// DO NOT EDIT!


#ifndef FREMENSERVER_MESSAGE_FREMENACTIONGOAL_H
#define FREMENSERVER_MESSAGE_FREMENACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <fremenserver/FremenGoal.h>

namespace fremenserver
{
template <class ContainerAllocator>
struct FremenActionGoal_
{
  typedef FremenActionGoal_<ContainerAllocator> Type;

  FremenActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FremenActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::fremenserver::FremenGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::fremenserver::FremenActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fremenserver::FremenActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FremenActionGoal_

typedef ::fremenserver::FremenActionGoal_<std::allocator<void> > FremenActionGoal;

typedef boost::shared_ptr< ::fremenserver::FremenActionGoal > FremenActionGoalPtr;
typedef boost::shared_ptr< ::fremenserver::FremenActionGoal const> FremenActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fremenserver::FremenActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fremenserver::FremenActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fremenserver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'fremenserver': ['/home/adrian/test_ws/devel/share/fremenserver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fremenserver::FremenActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fremenserver::FremenActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fremenserver::FremenActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "853d97f390d9ef38dfe24cf2d126d07b";
  }

  static const char* value(const ::fremenserver::FremenActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x853d97f390d9ef38ULL;
  static const uint64_t static_value2 = 0xdfe24cf2d126d07bULL;
};

template<class ContainerAllocator>
struct DataType< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fremenserver/FremenActionGoal";
  }

  static const char* value(const ::fremenserver::FremenActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FremenGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: fremenserver/FremenGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
string   operation 	#the operation can be 'add', 'addvalues', 'predict', 'forecast', 'entropy', 'evaluate', 'detect', 'update', 'delete'\n\
			#'add' adds a sequence of given (by ID) state measurements and the times these have been obtained to the state's model, if ID is given for the first time, a new state is created and added to the model\n\
			#'addvalues' adds a sequence of given (by ID) value measurements and the times these have been obtained to the state's model, if ID is given for the first time, a new state is created and added to the model\n\
			#'predict'  calculates a sequence of probabilities of the state ID for the given times (i.e. prediction of one state for multiple time instants)\n\
			#'forecast'  calculates a sequence of probabilities of the states with given 'ids' for the given time (i.e. prediction of mutiple states for a single time instant)\n\
			#'entropy'  calculates a sequence of entropies of the state ID for the given times - this is to support exploration\n\
			#'evaluate' predicts the state for the given times, compares the prediction with ground truth and returns the prediction errors for model orders from 0 to the order specified. Meant to help to decide which order to use for the 'predict' action. \n\
			#'detect' detects anomalies by predicting the state for the given times, comparing with ground truth and flagging up discrepancies that were beyond a certain 'confidence' level \n\
			#'delete' removes the current state from the collection of states   \n\
			#'update' is reserved, will be used int the future for recalculating the models\n\
\n\
string  id	  	#specifies the ID of the state to be manipulated \n\
string[]  ids	  	#specifies the IDs of the states to be manipulated - explusively fot the 'forecast' action\n\
uint32[]  times 	#the time instants for the 'predict', 'add', 'entropy' and 'evaluate' actions\n\
\n\
#specific for the 'predict', 'evaluate' and 'detect' actions\n\
int32    order 		#number of periodic processes to use for the purpose of prediction (0 means a static model, typical value is 2), maximal order used for evaluation of the 'evaluate' action\n\
\n\
#specific for the 'forecast' actions\n\
int32[]  orders	  	#same as previous one, but for all states in the **ids** \n\
\n\
#specific for the 'add' and 'evaluate' action\n\
bool[]      states   	#sequence of states observed at the particular times - specific to the 'add' action 	(this is for backward compatibility)\n\
float32[]   values   	#sequence of values observed at the particular times - specific to the 'addvalues' action, (I recommend to normalize the values so they fit 0-1)\n\
\n\
#specific for the 'detect' \n\
float32   confidence   	#confidence level for the anomaly detection\n\
\n\
#specific for the 'upload_params'\n\
float32[] periods\n\
float32[] amplitudes\n\
float32[] phases\n\
\n\
";
  }

  static const char* value(const ::fremenserver::FremenActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FremenActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fremenserver::FremenActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fremenserver::FremenActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::fremenserver::FremenGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FREMENSERVER_MESSAGE_FREMENACTIONGOAL_H
