// Generated by gencpp from file frongo/AddCell.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_ADDCELL_H
#define FRONGO_MESSAGE_ADDCELL_H

#include <ros/service_traits.h>


#include <frongo/AddCellRequest.h>
#include <frongo/AddCellResponse.h>


namespace frongo
{

struct AddCell
{

typedef AddCellRequest Request;
typedef AddCellResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddCell
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::AddCell > {
  static const char* value()
  {
    return "9703095a7d44bb2a973590113ee73ad2";
  }

  static const char* value(const ::frongo::AddCell&) { return value(); }
};

template<>
struct DataType< ::frongo::AddCell > {
  static const char* value()
  {
    return "frongo/AddCell";
  }

  static const char* value(const ::frongo::AddCell&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::AddCellRequest> should match 
// service_traits::MD5Sum< ::frongo::AddCell > 
template<>
struct MD5Sum< ::frongo::AddCellRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddCell >::value();
  }
  static const char* value(const ::frongo::AddCellRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddCellRequest> should match 
// service_traits::DataType< ::frongo::AddCell > 
template<>
struct DataType< ::frongo::AddCellRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::AddCell >::value();
  }
  static const char* value(const ::frongo::AddCellRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::AddCellResponse> should match 
// service_traits::MD5Sum< ::frongo::AddCell > 
template<>
struct MD5Sum< ::frongo::AddCellResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddCell >::value();
  }
  static const char* value(const ::frongo::AddCellResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddCellResponse> should match 
// service_traits::DataType< ::frongo::AddCell > 
template<>
struct DataType< ::frongo::AddCellResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::AddCell >::value();
  }
  static const char* value(const ::frongo::AddCellResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_ADDCELL_H
