// Generated by gencpp from file frongo/AddModel.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_ADDMODEL_H
#define FRONGO_MESSAGE_ADDMODEL_H

#include <ros/service_traits.h>


#include <frongo/AddModelRequest.h>
#include <frongo/AddModelResponse.h>


namespace frongo
{

struct AddModel
{

typedef AddModelRequest Request;
typedef AddModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddModel
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::AddModel > {
  static const char* value()
  {
    return "9703095a7d44bb2a973590113ee73ad2";
  }

  static const char* value(const ::frongo::AddModel&) { return value(); }
};

template<>
struct DataType< ::frongo::AddModel > {
  static const char* value()
  {
    return "frongo/AddModel";
  }

  static const char* value(const ::frongo::AddModel&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::AddModelRequest> should match 
// service_traits::MD5Sum< ::frongo::AddModel > 
template<>
struct MD5Sum< ::frongo::AddModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddModel >::value();
  }
  static const char* value(const ::frongo::AddModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddModelRequest> should match 
// service_traits::DataType< ::frongo::AddModel > 
template<>
struct DataType< ::frongo::AddModelRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::AddModel >::value();
  }
  static const char* value(const ::frongo::AddModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::AddModelResponse> should match 
// service_traits::MD5Sum< ::frongo::AddModel > 
template<>
struct MD5Sum< ::frongo::AddModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddModel >::value();
  }
  static const char* value(const ::frongo::AddModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddModelResponse> should match 
// service_traits::DataType< ::frongo::AddModel > 
template<>
struct DataType< ::frongo::AddModelResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::AddModel >::value();
  }
  static const char* value(const ::frongo::AddModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_ADDMODEL_H
