// Generated by gencpp from file frongo/AddModelRequest.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_ADDMODELREQUEST_H
#define FRONGO_MESSAGE_ADDMODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace frongo
{
template <class ContainerAllocator>
struct AddModelRequest_
{
  typedef AddModelRequest_<ContainerAllocator> Type;

  AddModelRequest_()
    : model_def()  {
    }
  AddModelRequest_(const ContainerAllocator& _alloc)
    : model_def(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_def_type;
  _model_def_type model_def;





  typedef boost::shared_ptr< ::frongo::AddModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frongo::AddModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddModelRequest_

typedef ::frongo::AddModelRequest_<std::allocator<void> > AddModelRequest;

typedef boost::shared_ptr< ::frongo::AddModelRequest > AddModelRequestPtr;
typedef boost::shared_ptr< ::frongo::AddModelRequest const> AddModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frongo::AddModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frongo::AddModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace frongo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::frongo::AddModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frongo::AddModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::AddModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::AddModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::AddModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::AddModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frongo::AddModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c9aaacc4b3ab02bc57e71b52879e835";
  }

  static const char* value(const ::frongo::AddModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c9aaacc4b3ab02bULL;
  static const uint64_t static_value2 = 0xc57e71b52879e835ULL;
};

template<class ContainerAllocator>
struct DataType< ::frongo::AddModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frongo/AddModelRequest";
  }

  static const char* value(const ::frongo::AddModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frongo::AddModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_def\n\
";
  }

  static const char* value(const ::frongo::AddModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frongo::AddModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_def);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frongo::AddModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frongo::AddModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_def: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model_def);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRONGO_MESSAGE_ADDMODELREQUEST_H
