// Generated by gencpp from file frongo/AddOccupancyGrid.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_ADDOCCUPANCYGRID_H
#define FRONGO_MESSAGE_ADDOCCUPANCYGRID_H

#include <ros/service_traits.h>


#include <frongo/AddOccupancyGridRequest.h>
#include <frongo/AddOccupancyGridResponse.h>


namespace frongo
{

struct AddOccupancyGrid
{

typedef AddOccupancyGridRequest Request;
typedef AddOccupancyGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddOccupancyGrid
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::AddOccupancyGrid > {
  static const char* value()
  {
    return "d80d29e273fcfeeabf6b0b84dde04fa1";
  }

  static const char* value(const ::frongo::AddOccupancyGrid&) { return value(); }
};

template<>
struct DataType< ::frongo::AddOccupancyGrid > {
  static const char* value()
  {
    return "frongo/AddOccupancyGrid";
  }

  static const char* value(const ::frongo::AddOccupancyGrid&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::AddOccupancyGridRequest> should match 
// service_traits::MD5Sum< ::frongo::AddOccupancyGrid > 
template<>
struct MD5Sum< ::frongo::AddOccupancyGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddOccupancyGrid >::value();
  }
  static const char* value(const ::frongo::AddOccupancyGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddOccupancyGridRequest> should match 
// service_traits::DataType< ::frongo::AddOccupancyGrid > 
template<>
struct DataType< ::frongo::AddOccupancyGridRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::AddOccupancyGrid >::value();
  }
  static const char* value(const ::frongo::AddOccupancyGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::AddOccupancyGridResponse> should match 
// service_traits::MD5Sum< ::frongo::AddOccupancyGrid > 
template<>
struct MD5Sum< ::frongo::AddOccupancyGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::AddOccupancyGrid >::value();
  }
  static const char* value(const ::frongo::AddOccupancyGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::AddOccupancyGridResponse> should match 
// service_traits::DataType< ::frongo::AddOccupancyGrid > 
template<>
struct DataType< ::frongo::AddOccupancyGridResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::AddOccupancyGrid >::value();
  }
  static const char* value(const ::frongo::AddOccupancyGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_ADDOCCUPANCYGRID_H
