// Generated by gencpp from file frongo/EvaluateModels.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_EVALUATEMODELS_H
#define FRONGO_MESSAGE_EVALUATEMODELS_H

#include <ros/service_traits.h>


#include <frongo/EvaluateModelsRequest.h>
#include <frongo/EvaluateModelsResponse.h>


namespace frongo
{

struct EvaluateModels
{

typedef EvaluateModelsRequest Request;
typedef EvaluateModelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EvaluateModels
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::EvaluateModels > {
  static const char* value()
  {
    return "b39707c144dc811845d1401dd6f773fb";
  }

  static const char* value(const ::frongo::EvaluateModels&) { return value(); }
};

template<>
struct DataType< ::frongo::EvaluateModels > {
  static const char* value()
  {
    return "frongo/EvaluateModels";
  }

  static const char* value(const ::frongo::EvaluateModels&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::EvaluateModelsRequest> should match 
// service_traits::MD5Sum< ::frongo::EvaluateModels > 
template<>
struct MD5Sum< ::frongo::EvaluateModelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::EvaluateModels >::value();
  }
  static const char* value(const ::frongo::EvaluateModelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::EvaluateModelsRequest> should match 
// service_traits::DataType< ::frongo::EvaluateModels > 
template<>
struct DataType< ::frongo::EvaluateModelsRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::EvaluateModels >::value();
  }
  static const char* value(const ::frongo::EvaluateModelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::EvaluateModelsResponse> should match 
// service_traits::MD5Sum< ::frongo::EvaluateModels > 
template<>
struct MD5Sum< ::frongo::EvaluateModelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::EvaluateModels >::value();
  }
  static const char* value(const ::frongo::EvaluateModelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::EvaluateModelsResponse> should match 
// service_traits::DataType< ::frongo::EvaluateModels > 
template<>
struct DataType< ::frongo::EvaluateModelsResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::EvaluateModels >::value();
  }
  static const char* value(const ::frongo::EvaluateModelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_EVALUATEMODELS_H
