// Generated by gencpp from file frongo/GetModelNameRequest.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_GETMODELNAMEREQUEST_H
#define FRONGO_MESSAGE_GETMODELNAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace frongo
{
template <class ContainerAllocator>
struct GetModelNameRequest_
{
  typedef GetModelNameRequest_<ContainerAllocator> Type;

  GetModelNameRequest_()
    : model_name()
    , random_string()  {
    }
  GetModelNameRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)
    , random_string(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_name_type;
  _model_name_type model_name;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _random_string_type;
  _random_string_type random_string;





  typedef boost::shared_ptr< ::frongo::GetModelNameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frongo::GetModelNameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetModelNameRequest_

typedef ::frongo::GetModelNameRequest_<std::allocator<void> > GetModelNameRequest;

typedef boost::shared_ptr< ::frongo::GetModelNameRequest > GetModelNameRequestPtr;
typedef boost::shared_ptr< ::frongo::GetModelNameRequest const> GetModelNameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frongo::GetModelNameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frongo::GetModelNameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace frongo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::frongo::GetModelNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frongo::GetModelNameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::GetModelNameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::GetModelNameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::GetModelNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::GetModelNameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frongo::GetModelNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e334af7af63b0a6c211a5bd62d351ec";
  }

  static const char* value(const ::frongo::GetModelNameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e334af7af63b0a6ULL;
  static const uint64_t static_value2 = 0xc211a5bd62d351ecULL;
};

template<class ContainerAllocator>
struct DataType< ::frongo::GetModelNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frongo/GetModelNameRequest";
  }

  static const char* value(const ::frongo::GetModelNameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frongo::GetModelNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_name\n\
uint32[] random_string\n\
";
  }

  static const char* value(const ::frongo::GetModelNameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frongo::GetModelNameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
      stream.next(m.random_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModelNameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frongo::GetModelNameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frongo::GetModelNameRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model_name);
    s << indent << "random_string[]" << std::endl;
    for (size_t i = 0; i < v.random_string.size(); ++i)
    {
      s << indent << "  random_string[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.random_string[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRONGO_MESSAGE_GETMODELNAMEREQUEST_H
