// Generated by gencpp from file frongo/GetModelName.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_GETMODELNAME_H
#define FRONGO_MESSAGE_GETMODELNAME_H

#include <ros/service_traits.h>


#include <frongo/GetModelNameRequest.h>
#include <frongo/GetModelNameResponse.h>


namespace frongo
{

struct GetModelName
{

typedef GetModelNameRequest Request;
typedef GetModelNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetModelName
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::GetModelName > {
  static const char* value()
  {
    return "9018f8bdc32329b5f34846c1b72a4a9c";
  }

  static const char* value(const ::frongo::GetModelName&) { return value(); }
};

template<>
struct DataType< ::frongo::GetModelName > {
  static const char* value()
  {
    return "frongo/GetModelName";
  }

  static const char* value(const ::frongo::GetModelName&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::GetModelNameRequest> should match 
// service_traits::MD5Sum< ::frongo::GetModelName > 
template<>
struct MD5Sum< ::frongo::GetModelNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::GetModelName >::value();
  }
  static const char* value(const ::frongo::GetModelNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::GetModelNameRequest> should match 
// service_traits::DataType< ::frongo::GetModelName > 
template<>
struct DataType< ::frongo::GetModelNameRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::GetModelName >::value();
  }
  static const char* value(const ::frongo::GetModelNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::GetModelNameResponse> should match 
// service_traits::MD5Sum< ::frongo::GetModelName > 
template<>
struct MD5Sum< ::frongo::GetModelNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::GetModelName >::value();
  }
  static const char* value(const ::frongo::GetModelNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::GetModelNameResponse> should match 
// service_traits::DataType< ::frongo::GetModelName > 
template<>
struct DataType< ::frongo::GetModelNameResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::GetModelName >::value();
  }
  static const char* value(const ::frongo::GetModelNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_GETMODELNAME_H
