// Generated by gencpp from file frongo/GraphModel.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_GRAPHMODEL_H
#define FRONGO_MESSAGE_GRAPHMODEL_H

#include <ros/service_traits.h>


#include <frongo/GraphModelRequest.h>
#include <frongo/GraphModelResponse.h>


namespace frongo
{

struct GraphModel
{

typedef GraphModelRequest Request;
typedef GraphModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraphModel
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::GraphModel > {
  static const char* value()
  {
    return "12c8011e5f49767d0aa831627309e4d7";
  }

  static const char* value(const ::frongo::GraphModel&) { return value(); }
};

template<>
struct DataType< ::frongo::GraphModel > {
  static const char* value()
  {
    return "frongo/GraphModel";
  }

  static const char* value(const ::frongo::GraphModel&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::GraphModelRequest> should match 
// service_traits::MD5Sum< ::frongo::GraphModel > 
template<>
struct MD5Sum< ::frongo::GraphModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::GraphModel >::value();
  }
  static const char* value(const ::frongo::GraphModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::GraphModelRequest> should match 
// service_traits::DataType< ::frongo::GraphModel > 
template<>
struct DataType< ::frongo::GraphModelRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::GraphModel >::value();
  }
  static const char* value(const ::frongo::GraphModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::GraphModelResponse> should match 
// service_traits::MD5Sum< ::frongo::GraphModel > 
template<>
struct MD5Sum< ::frongo::GraphModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::GraphModel >::value();
  }
  static const char* value(const ::frongo::GraphModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::GraphModelResponse> should match 
// service_traits::DataType< ::frongo::GraphModel > 
template<>
struct DataType< ::frongo::GraphModelResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::GraphModel >::value();
  }
  static const char* value(const ::frongo::GraphModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_GRAPHMODEL_H
