// Generated by gencpp from file frongo/PredictStateOrderResponse.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_PREDICTSTATEORDERRESPONSE_H
#define FRONGO_MESSAGE_PREDICTSTATEORDERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace frongo
{
template <class ContainerAllocator>
struct PredictStateOrderResponse_
{
  typedef PredictStateOrderResponse_<ContainerAllocator> Type;

  PredictStateOrderResponse_()
    : epochs()
    , predictions()  {
    }
  PredictStateOrderResponse_(const ContainerAllocator& _alloc)
    : epochs(_alloc)
    , predictions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _epochs_type;
  _epochs_type epochs;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _predictions_type;
  _predictions_type predictions;





  typedef boost::shared_ptr< ::frongo::PredictStateOrderResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::frongo::PredictStateOrderResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PredictStateOrderResponse_

typedef ::frongo::PredictStateOrderResponse_<std::allocator<void> > PredictStateOrderResponse;

typedef boost::shared_ptr< ::frongo::PredictStateOrderResponse > PredictStateOrderResponsePtr;
typedef boost::shared_ptr< ::frongo::PredictStateOrderResponse const> PredictStateOrderResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::frongo::PredictStateOrderResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace frongo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::frongo::PredictStateOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::frongo::PredictStateOrderResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::frongo::PredictStateOrderResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0451b77ac97886a262f9931253e48a0";
  }

  static const char* value(const ::frongo::PredictStateOrderResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0451b77ac97886aULL;
  static const uint64_t static_value2 = 0x262f9931253e48a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "frongo/PredictStateOrderResponse";
  }

  static const char* value(const ::frongo::PredictStateOrderResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] epochs\n\
float64[] predictions\n\
\n\
";
  }

  static const char* value(const ::frongo::PredictStateOrderResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.epochs);
      stream.next(m.predictions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictStateOrderResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::frongo::PredictStateOrderResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::frongo::PredictStateOrderResponse_<ContainerAllocator>& v)
  {
    s << indent << "epochs[]" << std::endl;
    for (size_t i = 0; i < v.epochs.size(); ++i)
    {
      s << indent << "  epochs[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.epochs[i]);
    }
    s << indent << "predictions[]" << std::endl;
    for (size_t i = 0; i < v.predictions.size(); ++i)
    {
      s << indent << "  predictions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.predictions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRONGO_MESSAGE_PREDICTSTATEORDERRESPONSE_H
