// Generated by gencpp from file frongo/PredictStateOrder.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_PREDICTSTATEORDER_H
#define FRONGO_MESSAGE_PREDICTSTATEORDER_H

#include <ros/service_traits.h>


#include <frongo/PredictStateOrderRequest.h>
#include <frongo/PredictStateOrderResponse.h>


namespace frongo
{

struct PredictStateOrder
{

typedef PredictStateOrderRequest Request;
typedef PredictStateOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredictStateOrder
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::PredictStateOrder > {
  static const char* value()
  {
    return "ae1fcb161afd95e17d99e9fd38349e36";
  }

  static const char* value(const ::frongo::PredictStateOrder&) { return value(); }
};

template<>
struct DataType< ::frongo::PredictStateOrder > {
  static const char* value()
  {
    return "frongo/PredictStateOrder";
  }

  static const char* value(const ::frongo::PredictStateOrder&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::PredictStateOrderRequest> should match 
// service_traits::MD5Sum< ::frongo::PredictStateOrder > 
template<>
struct MD5Sum< ::frongo::PredictStateOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::PredictStateOrder >::value();
  }
  static const char* value(const ::frongo::PredictStateOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::PredictStateOrderRequest> should match 
// service_traits::DataType< ::frongo::PredictStateOrder > 
template<>
struct DataType< ::frongo::PredictStateOrderRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::PredictStateOrder >::value();
  }
  static const char* value(const ::frongo::PredictStateOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::PredictStateOrderResponse> should match 
// service_traits::MD5Sum< ::frongo::PredictStateOrder > 
template<>
struct MD5Sum< ::frongo::PredictStateOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::PredictStateOrder >::value();
  }
  static const char* value(const ::frongo::PredictStateOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::PredictStateOrderResponse> should match 
// service_traits::DataType< ::frongo::PredictStateOrder > 
template<>
struct DataType< ::frongo::PredictStateOrderResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::PredictStateOrder >::value();
  }
  static const char* value(const ::frongo::PredictStateOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_PREDICTSTATEORDER_H
