// Generated by gencpp from file frongo/SaveGrid.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_SAVEGRID_H
#define FRONGO_MESSAGE_SAVEGRID_H

#include <ros/service_traits.h>


#include <frongo/SaveGridRequest.h>
#include <frongo/SaveGridResponse.h>


namespace frongo
{

struct SaveGrid
{

typedef SaveGridRequest Request;
typedef SaveGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveGrid
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::SaveGrid > {
  static const char* value()
  {
    return "6090d744392c14e9793f5e7c1616c9e2";
  }

  static const char* value(const ::frongo::SaveGrid&) { return value(); }
};

template<>
struct DataType< ::frongo::SaveGrid > {
  static const char* value()
  {
    return "frongo/SaveGrid";
  }

  static const char* value(const ::frongo::SaveGrid&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::SaveGridRequest> should match 
// service_traits::MD5Sum< ::frongo::SaveGrid > 
template<>
struct MD5Sum< ::frongo::SaveGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::SaveGrid >::value();
  }
  static const char* value(const ::frongo::SaveGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::SaveGridRequest> should match 
// service_traits::DataType< ::frongo::SaveGrid > 
template<>
struct DataType< ::frongo::SaveGridRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::SaveGrid >::value();
  }
  static const char* value(const ::frongo::SaveGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::SaveGridResponse> should match 
// service_traits::MD5Sum< ::frongo::SaveGrid > 
template<>
struct MD5Sum< ::frongo::SaveGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::SaveGrid >::value();
  }
  static const char* value(const ::frongo::SaveGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::SaveGridResponse> should match 
// service_traits::DataType< ::frongo::SaveGrid > 
template<>
struct DataType< ::frongo::SaveGridResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::SaveGrid >::value();
  }
  static const char* value(const ::frongo::SaveGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_SAVEGRID_H
