// Generated by gencpp from file frongo/UploadGrid.msg
// DO NOT EDIT!


#ifndef FRONGO_MESSAGE_UPLOADGRID_H
#define FRONGO_MESSAGE_UPLOADGRID_H

#include <ros/service_traits.h>


#include <frongo/UploadGridRequest.h>
#include <frongo/UploadGridResponse.h>


namespace frongo
{

struct UploadGrid
{

typedef UploadGridRequest Request;
typedef UploadGridResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadGrid
} // namespace frongo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::frongo::UploadGrid > {
  static const char* value()
  {
    return "6090d744392c14e9793f5e7c1616c9e2";
  }

  static const char* value(const ::frongo::UploadGrid&) { return value(); }
};

template<>
struct DataType< ::frongo::UploadGrid > {
  static const char* value()
  {
    return "frongo/UploadGrid";
  }

  static const char* value(const ::frongo::UploadGrid&) { return value(); }
};


// service_traits::MD5Sum< ::frongo::UploadGridRequest> should match 
// service_traits::MD5Sum< ::frongo::UploadGrid > 
template<>
struct MD5Sum< ::frongo::UploadGridRequest>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::UploadGrid >::value();
  }
  static const char* value(const ::frongo::UploadGridRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::UploadGridRequest> should match 
// service_traits::DataType< ::frongo::UploadGrid > 
template<>
struct DataType< ::frongo::UploadGridRequest>
{
  static const char* value()
  {
    return DataType< ::frongo::UploadGrid >::value();
  }
  static const char* value(const ::frongo::UploadGridRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::frongo::UploadGridResponse> should match 
// service_traits::MD5Sum< ::frongo::UploadGrid > 
template<>
struct MD5Sum< ::frongo::UploadGridResponse>
{
  static const char* value()
  {
    return MD5Sum< ::frongo::UploadGrid >::value();
  }
  static const char* value(const ::frongo::UploadGridResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::frongo::UploadGridResponse> should match 
// service_traits::DataType< ::frongo::UploadGrid > 
template<>
struct DataType< ::frongo::UploadGridResponse>
{
  static const char* value()
  {
    return DataType< ::frongo::UploadGrid >::value();
  }
  static const char* value(const ::frongo::UploadGridResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRONGO_MESSAGE_UPLOADGRID_H
